/**
 * app/api/admin/users/route.ts
 *
 * GET  /api/admin/users?q=&cursor=&limit=
 * POST /api/admin/users  body: { username, password?, role?, displayName? }
 */
import { NextResponse } from "next/server";
import { z } from "zod";
import { createUser, listUsers } from "@/lib/db/users";
import { generateInitialPassword } from "@/lib/crypto/password";
import { toPublicUser } from "@/lib/db/types";
import { getCurrentUser } from "@/lib/auth/session";

const PostSchema = z.object({
  username: z.string().min(3).max(32),
  password: z.string().optional(),
  role: z.enum(["admin", "user"]).optional(),
  displayName: z.string().optional(),
  // Optional initial allocation. Omit to create the account with an empty
  // pool — the admin can grant credits later from the allocation editor.
  quotaType: z.enum(["credits", "tokens"]).optional(),
  quotaLimit: z.number().int().nonnegative().optional(),
  maxActiveKeys: z.number().int().nonnegative().optional(),
  allowedModels: z.array(z.string()).optional(),
});

export async function GET(req: Request): Promise<Response> {
  const me = await getCurrentUser();
  if (!me || me.role !== "admin") {
    return NextResponse.json(
      { ok: false, error: { code: "forbidden", message: "Admin required" } },
      { status: 403 },
    );
  }

  const url = new URL(req.url);
  const limit = Math.max(1, Math.min(Number(url.searchParams.get("limit") ?? "50"), 200));
  const cursor = url.searchParams.get("cursor") ?? undefined;

  const { users, nextCursor } = await listUsers({ limit, cursor });
  return NextResponse.json({
    ok: true,
    data: { users: users.map(toPublicUser), nextCursor },
  });
}

export async function POST(req: Request): Promise<Response> {
  const me = await getCurrentUser();
  if (!me || me.role !== "admin") {
    return NextResponse.json(
      { ok: false, error: { code: "forbidden", message: "Admin required" } },
      { status: 403 },
    );
  }

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json(
      { ok: false, error: { code: "bad_json", message: "Invalid JSON" } },
      { status: 400 },
    );
  }

  const parsed = PostSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      { ok: false, error: { code: "bad_request", message: parsed.error.message } },
      { status: 400 },
    );
  }

  // Auto-generate a strong password when admin doesn't supply one.
  const password = parsed.data.password ?? generateInitialPassword();
  const isAutoGenerated = parsed.data.password === undefined;

  try {
    const user = await createUser({
      username: parsed.data.username,
      password,
      role: parsed.data.role,
      displayName: parsed.data.displayName,
      quotaType: parsed.data.quotaType,
      quotaLimit: parsed.data.quotaLimit,
      maxActiveKeys: parsed.data.maxActiveKeys,
      allowedModels: parsed.data.allowedModels,
    });
    return NextResponse.json({
      ok: true,
      data: {
        user: toPublicUser(user),
        ...(isAutoGenerated ? { generatedPassword: password } : {}),
      },
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : "Unknown error";
    if (msg.includes("already exists")) {
      return NextResponse.json(
        { ok: false, error: { code: "username_conflict", message: msg } },
        { status: 409 },
      );
    }
    return NextResponse.json(
      { ok: false, error: { code: "internal_error", message: msg } },
      { status: 500 },
    );
  }
}
