/**
 * src/lib/db/assistant-keys.ts
 *
 * The credential the assistant spends on a user's behalf, authorised by their
 * session rather than by a secret they had to paste.
 *
 * Why it is a row in `api_keys` and not a new kind of thing: usage and quota
 * are accounted per key. `usage_logs.api_key_id` is NOT NULL and `usage_totals`
 * is keyed by it, and the proxy reads that on every single request, so
 * attributing assistant calls to "no key" would have meant reworking the
 * hottest path in the product to accommodate one feature. Pointing at a real row
 * keeps every existing policy check, whitelist and ledger entry working
 * unchanged — the assistant is simply another caller of a key that belongs to
 * the user.
 *
 * Why it is nevertheless not a usable key: the plaintext is generated by
 * `createApiKey` and dropped on the floor. The row keeps only its sha256, of a
 * secret nobody ever sees, so the row can never authenticate a bearer request
 * and there is nothing for anyone to copy. The assistant holds the `ApiKey`
 * object itself and calls the proxy in-process. That is also why the only way
 * to change the credential is to replace it.
 *
 * Consequences worth stating, because they are the whole design:
 *   - The plaintext is unrecoverable by construction, not by policy. There is
 *     no "reveal" to get wrong, and no stored secret to leak with a backup.
 *   - "Rebuild" means a different key, not the same one re-shown.
 *   - The user's own key list omits it (see `listApiKeysByUser`), so it does
 *     not eat into their `maxActiveKeys` budget and cannot be used by them.
 *   - It is NOT hidden from admins, and is labelled so: an admin has to be able
 *     to see that a user switched this on and revoke it with the existing
 *     delete button, which cascades.
 */
import { createApiKey, deleteApiKey, getApiKeyById, updateApiKey } from "./keys";
import { fromDbBool, getOne, run, rowToApiKey, toDbBool, withTransaction } from "./sqlite";
import type { ApiKey } from "./types";

/**
 * Label the assistant credential carries in the admin key list, where it is
 * visible and has to be self-explanatory. Hidden from the owning user, so no
 * localisation is needed for it.
 */
export const ASSISTANT_KEY_LABEL = "AI 助手专用";

export interface AssistantCredential {
  userId: string;
  /** The `api_keys` row usage is attributed to. */
  apiKeyId: string;
  /** The user's own switch. Off means the assistant may not spend it. */
  enabled: boolean;
  createdAt: string;
  key: ApiKey;
}

/**
 * The caller's credential, or null when they never created one.
 *
 * Returns null for a dangling pointer rather than throwing: an admin can delete
 * the underlying key out from under this table, and the assistant should then
 * behave exactly as it does for a user who never opted in — not fail the turn.
 */
export async function getAssistantCredential(userId: string): Promise<AssistantCredential | null> {
  if (!userId) return null;
  const row = getOne<{
    user_id: string;
    api_key_id: string;
    enabled: number;
    created_at: string;
  }>("SELECT * FROM assistant_keys WHERE user_id = ?", [userId]);
  if (!row) return null;

  const key = await getApiKeyById(row.api_key_id);
  if (!key) return null;

  return {
    userId: row.user_id,
    apiKeyId: row.api_key_id,
    enabled: fromDbBool(row.enabled),
    createdAt: row.created_at,
    key,
  };
}

/** True when the assistant is allowed to spend this user's quota. */
export async function isAssistantCredentialEnabled(userId: string): Promise<boolean> {
  return (await getAssistantCredential(userId))?.enabled === true;
}

/**
 * Create the credential. Off by default: the user turning it on is a separate,
 * explicit act (see `setAssistantCredentialEnabled`).
 *
 * Idempotent in the sense that matters — calling it for a user who already has
 * one returns the existing credential rather than minting a second, so a double
 * click cannot quietly leave an orphan key behind. Use `rotate` to replace.
 */
export async function createAssistantCredential(userId: string): Promise<AssistantCredential> {
  const existing = await getAssistantCredential(userId);
  if (existing) return existing;

  // The api_keys row and the assistant_keys row must appear together: the
  // second is meaningless without the first, and an orphaned api_keys row would
  // be a key the user cannot see and nobody can explain.
  return withTransaction(async () => {
    const { key } = await createApiKey({ userId, label: ASSISTANT_KEY_LABEL });
    run(
      `INSERT INTO assistant_keys (user_id, api_key_id, enabled, created_at)
       VALUES (?, ?, 0, ?)`,
      [userId, key.id, new Date().toISOString()],
    );
    return {
      userId,
      apiKeyId: key.id,
      enabled: false,
      createdAt: new Date().toISOString(),
      key,
    };
  });
}

/**
 * The user's switch. Turning it on also enables the underlying key so the admin
 * key list mirrors the state rather than showing a live credential the user
 * believes is off; turning it off disables the key for the same reason.
 */
export async function setAssistantCredentialEnabled(
  userId: string,
  enabled: boolean,
): Promise<AssistantCredential | null> {
  const current = await getAssistantCredential(userId);
  if (!current) return null;
  await updateApiKey(current.apiKeyId, { enabled });
  run("UPDATE assistant_keys SET enabled = ? WHERE user_id = ?", [enabled ? 1 : 0, userId]);
  return { ...current, enabled };
}

/**
 * Replace the credential with a fresh one, keeping its on/off state.
 *
 * The old `api_keys` row is deleted rather than disabled so its usage history
 * does not linger as a second key the admin can see. SQLite has no FK on
 * `usage_logs.api_key_id`, so the ledger rows survive; only the identity goes.
 */
export async function rotateAssistantCredential(userId: string): Promise<AssistantCredential | null> {
  const current = await getAssistantCredential(userId);
  if (!current) return null;

  return withTransaction(async () => {
    const { key } = await createApiKey({ userId, label: ASSISTANT_KEY_LABEL });
    run("UPDATE assistant_keys SET api_key_id = ?, created_at = ? WHERE user_id = ?", [
      key.id,
      new Date().toISOString(),
      userId,
    ]);
    run("DELETE FROM api_keys WHERE id = ?", [current.apiKeyId]);
    return { ...current, apiKeyId: key.id, key, createdAt: new Date().toISOString() };
  });
}

/** Remove the credential entirely. Both rows go, so nothing is left to explain. */
export async function removeAssistantCredential(userId: string): Promise<boolean> {
  const current = await getAssistantCredential(userId);
  if (!current) return false;
  await deleteApiKey(current.apiKeyId); // cascades into assistant_keys
  return true;
}
